### PR TITLE
Feat: Responsive Sidebar, Navbar 

### PR DESCRIPTION
**Pull request by dikshadhote**
Following Features are Added in this PR :
1. Desktop Navbar and Sidebar with routes to different pages
image
2 . Minimize and maximize Sidebar on toggle 
image
3.  Responsive UI for small devices 
image

### CODE REVIEW

**Review by MonikaJhingan — APPROVED** [review]
The Ui is looking very good and just a small suggestion please use var for colors. The logic is well implemented.Good job.

**Review by Omkar-Chaskar — APPROVED** [review]
Nice UI . And sidebar function as youtube sidebar. Well written  logic and easy  to read code for context. 
In CSS , Nicely use color variables and grid properties. to make UI responsive.
Good to merge

**Comment by dikshadhote** [comment]
> The Ui is looking very good and just a small suggestion please use var for colors. The logic is well implemented.Good job.

I have used variables for color everywhere. Where are you  particularly referring to?

**Comment by dikshadhote** [comment]
> Nice UI . And sidebar function as youtube sidebar. Well written logic and easy to read code for context. In CSS , Nicely use color variables and grid properties. to make UI responsive. Good to merge

Thanks Omkar

**Pull request merged**
